# Generated by Django 4.2.4 on 2023-08-19 14:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('pricingModel', models.CharField(max_length=200)),
                ('url', models.TextField(blank=True, null=True)),
                ('imageSrc', models.TextField(blank=True, null=True)),
                ('src', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tooltags', models.ManyToManyField(to='aiwebsite.tag')),
            ],
        ),
    ]
