# Generated by Django 4.2.4 on 2023-08-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='title',
        ),
    ]
