# Generated by Django 4.2.4 on 2023-08-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwebsite', '0004_pricing_alter_product_pricingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
